language: node_js
  - "8"
sudo: true
os: osx
cache: npm
scripts:
  - cd todo-application
  - npm install
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master